# Generated by Django 5.1.1 on 2024-09-30 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ratingandreview_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingAndReview',
            new_name='RateAndReview',
        ),
    ]
